apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: quakewatch-rules
  namespace: monitoring
spec:
  groups:
  - name: quakewatch-alerts
    rules:
    - alert: HighErrorRate
      expr: rate(flask_http_request_exceptions_total[5m]) > 0.1
      for: 2m
      labels: { severity: warning }
      annotations:
        summary: "High error rate"
        description: "Errors > 0.1/s"
